# Generated by Django 4.2.30 on 2026-07-24 03:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_user_bio_user_discord_handle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'uploaded_datasets',
            },
        ),
        migrations.CreateModel(
            name='ModelEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mae', models.FloatField(default=0.0)),
                ('mse', models.FloatField(default=0.0)),
                ('rmse', models.FloatField(default=0.0)),
                ('r2_score', models.FloatField(default=0.0)),
                ('directional_accuracy_pct', models.FloatField(default=0.0)),
                ('evaluated_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='users.modelversion')),
            ],
            options={
                'db_table': 'model_evaluations',
            },
        ),
        migrations.CreateModel(
            name='DatasetProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('interval', models.CharField(default='5m', max_length=10)),
                ('total_rows', models.IntegerField(default=0)),
                ('total_cols', models.IntegerField(default=0)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('null_count', models.IntegerField(default=0)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.uploadeddataset')),
            ],
            options={
                'db_table': 'dataset_properties',
            },
        ),
    ]
