# Generated by Django 4.2.30 on 2026-07-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_uploadeddataset_modelevaluation_datasetproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbotsubscription',
            name='auto_trade_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userbotsubscription',
            name='auto_trade_mode',
            field=models.CharField(default='paper', max_length=20),
        ),
        migrations.AddField(
            model_name='userbotsubscription',
            name='max_risk_pct',
            field=models.FloatField(default=1.0),
        ),
    ]
