# Generated by Django 4.2.30 on 2026-07-24 11:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userbotsubscription_auto_trade_enabled_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userpaperposition',
            table=None,
        ),
        migrations.CreateModel(
            name='SmartOrderExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('side', models.CharField(max_length=10)),
                ('total_quantity', models.FloatField()),
                ('executed_quantity', models.FloatField(default=0.0)),
                ('execution_style', models.CharField(default='twap', max_length=20)),
                ('execution_mode', models.CharField(default='PASSIVE_LIMIT', max_length=20)),
                ('benchmark_price', models.FloatField()),
                ('avg_fill_price', models.FloatField(default=0.0)),
                ('slippage_saved_usd', models.FloatField(default=0.0)),
                ('status', models.CharField(default='executing', max_length=20)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'smart_order_executions',
            },
        ),
    ]
