# Generated by Django 4.2.30 on 2026-07-27 21:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_update_bots_universal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Portfolio', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_currency', models.CharField(default='USD', max_length=10)),
                ('initial_balance', models.FloatField(default=10000.0)),
                ('current_balance', models.FloatField(default=10000.0)),
                ('total_equity', models.FloatField(default=10000.0)),
                ('total_profit_loss', models.FloatField(default=0.0)),
                ('realized_profit_loss', models.FloatField(default=0.0)),
                ('unrealized_profit_loss', models.FloatField(default=0.0)),
                ('total_return_percentage', models.FloatField(default=0.0)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Investment Portfolio',
                'verbose_name_plural': 'User Investment Portfolios',
                'db_table': 'portfolio',
            },
        ),
        migrations.AlterModelOptions(
            name='competitionentry',
            options={'verbose_name': 'Competition Entry', 'verbose_name_plural': 'Competition Entries'},
        ),
        migrations.AlterModelOptions(
            name='predictionaccuracy',
            options={'verbose_name': 'Prediction Accuracy Record', 'verbose_name_plural': 'Prediction Accuracy Records'},
        ),
        migrations.AlterModelOptions(
            name='predictionhistory',
            options={'verbose_name': 'Prediction History', 'verbose_name_plural': 'Prediction Histories'},
        ),
        migrations.AlterModelOptions(
            name='userpreferences',
            options={'verbose_name': 'User Preferences', 'verbose_name_plural': 'User Preferences Records'},
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'verbose_name': 'User Watchlist', 'verbose_name_plural': 'User Watchlists'},
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='name',
            field=models.CharField(default='My Watchlist', max_length=100),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='symbols',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='watchlist',
            table='portfolio_watchlist',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('transaction_type', models.CharField(default='Deposit', max_length=20)),
                ('asset', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.FloatField(default=0.0)),
                ('execution_price', models.FloatField(default=0.0)),
                ('total_amount', models.FloatField(default=0.0)),
                ('fees', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('notes', models.TextField(blank=True, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.portfolio')),
            ],
            options={
                'verbose_name': 'Portfolio Transaction',
                'verbose_name_plural': 'Portfolio Transactions',
                'db_table': 'portfolio_transaction',
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='owner',
            field=models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='ticker',
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='', max_length=20)),
                ('asset_class', models.CharField(default='stock', max_length=20)),
                ('quantity', models.FloatField(default=0.0)),
                ('average_entry_price', models.FloatField(default=0.0)),
                ('current_market_price', models.FloatField(default=0.0)),
                ('market_value', models.FloatField(default=0.0)),
                ('unrealized_profit_loss', models.FloatField(default=0.0)),
                ('allocation_percentage', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='users.portfolio')),
            ],
            options={
                'verbose_name': 'Portfolio Holding',
                'verbose_name_plural': 'Portfolio Holdings',
                'db_table': 'portfolio_holding',
                'unique_together': {('portfolio', 'symbol')},
            },
        ),
    ]
