# Generated by Django 4.2.30 on 2026-08-14 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_portfolio_alter_competitionentry_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("activated_by", models.CharField(max_length=128)),
                (
                    "deactivated_by",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("reason", models.TextField()),
                ("affected_accounts", models.JSONField(default=list)),
                ("new_orders_blocked", models.BooleanField(default=True)),
                ("close_positions", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-activated_at"],
            },
        ),
    ]
